### ISSUE TITLE
mtr 0.85 crash when using tcp mode

### ISSUE THREAD

**Issue by felixonmars** [traviscross/mtr#28]
Steps to reproduce:

```
# mtr -i0.01 -T 8.8.8.8
```

It crashed in about a second (SIGABRT).

Backtrace:

```
(gdb) bt
#0  0x00007f471e2df1c9 in raise () from /usr/lib/libc.so.6
#1  0x00007f471e2e05c8 in abort () from /usr/lib/libc.so.6
#2  0x00007f471e31d037 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f471e3a4e67 in __fortify_fail () from /usr/lib/libc.so.6
#4  0x00007f471e3a3070 in __chk_fail () from /usr/lib/libc.so.6
#5  0x00007f471e3a4dd7 in __fdelt_warn () from /usr/lib/libc.so.6
#6  0x000000000040786c in net_process_fds ()
#7  0x000000000040bae5 in select_loop ()
#8  0x0000000000402b7b in main ()
```

OS is Arch Linux x86_64, with glibc 2.17

**Comment by QwertyZW** [comment]
Running into this with 
```
~% mtr --version
mtr 0.86
```

**Comment by chrcoluk** [comment]
I have this problem FreeBSD 11.2, TCP mode with no other flags specified 

# mtr --version
mtr UNKNOWN

O_o, it is 0.92 tho.

**Comment by rewolff** [comment]
You can help me reproduce it by restating the command I need to try to get what you see. Maybe a cut-and-paste of both the command and the crashing output.
